version: '3.6'

services:
  web:
    build: .
    volumes:
      - ./src:/app
    ports:
      - '4000:4000'
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
