version: '3.6'

services:
  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - '4000:4000'
    depends_on:
      - db
    command:
      - ./run.sh

  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
